[package]
name = "superoptimusprime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7"
regex = "1.8.3"
strum = { version = "0.24.1", features = ["derive"] }
threadpool = "1.0"

